name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: sudo cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: wifi-password-linux # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/release/wifi-password
        # The desired behavior if no files are found using the provided path.
    #Available Options:
      #warn: Output a warning but do not fail the action
      #error: Fail the action with an error message
      #ignore: Do not output any warnings or errors, the action does not fail

        #if-no-files-found: # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
    #Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

        #retention-days: # optional
